# Generated by Django 5.1.6 on 2025-03-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_services_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='mainapp.maincity'),
        ),
    ]
