# Generated by Django 5.1.6 on 2025-03-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_userprofile_joined_date'),
        ('mainapp', '0003_alter_blog_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('problem', models.TextField()),
            ],
            options={
                'verbose_name': 'Help Support',
                'verbose_name_plural': 'Help Supports',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in local currency', max_digits=10, null=True)),
                ('trip_started_date', models.DateTimeField()),
                ('trip_end_date', models.DateTimeField()),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage or amount', max_digits=5)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.guideprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.userprofile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
