# Generated by Django 5.1.6 on 2025-03-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_helpsupport_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.location'),
        ),
    ]
