# Generated by Django 5.1.6 on 2025-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_transactions_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
