# Generated by Django 5.1.6 on 2025-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_helpsupport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='replied',
            field=models.TextField(blank=True, null=True),
        ),
    ]
