# Generated by Django 5.1.6 on 2025-03-12 15:25

import cloudinary.models
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_helpsupport_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ummrah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ummrah')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ummrah',
                'verbose_name_plural': 'ummrah',
            },
        ),
    ]
