# Generated by Django 5.1.6 on 2025-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_ummrah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='location',
        ),
        migrations.AddField(
            model_name='transactions',
            name='locations',
            field=models.ManyToManyField(blank=True, to='mainapp.location'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Ongoing', 'Ongoing'), ('Payment', 'Payment')], default='Pending', max_length=20),
        ),
    ]
