# Generated by Django 5.1.6 on 2025-03-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_transactions_location_transactions_locations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
