# Generated by Django 5.1.6 on 2025-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='locations',
            field=models.ManyToManyField(blank=True, to='mainapp.services'),
        ),
    ]
