# Generated by Django 5.1.6 on 2025-03-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_transactions_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='locations',
            new_name='services',
        ),
    ]
