# Generated by Django 5.1.6 on 2025-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_calendaravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
