# Generated by Django 5.1.6 on 2025-04-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_transactions_created_at_transactions_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
