# Generated by Django 5.1.6 on 2025-03-09 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chat_id',
            field=models.UUIDField(default=uuid.UUID('9eb6930a-8136-44b7-84f8-d4c73914ec2c'), editable=False, unique=True),
        ),
    ]
