# Generated by Django 5.1.6 on 2025-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chathistory_chat_id_alter_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chat_id',
            field=models.UUIDField(editable=False),
        ),
    ]
