# Generated by Django 5.1.6 on 2025-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chathistory_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='reciver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
