# Generated by Django 5.1.6 on 2025-03-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chathistory_reciver_id_chathistory_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='reciver_id',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='sender_id',
        ),
    ]
