# Generated by Django 5.1.6 on 2025-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_guideprofile_image_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='guide_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
