# Generated by Django 5.1.6 on 2025-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_userprofile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='joined_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
