# Generated by Django 5.1.6 on 2025-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0009_alter_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
