# Generated by Django 5.1.6 on 2025-03-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='time_spend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
