# Generated by Django 5.1.6 on 2025-03-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='visible_at',
        ),
    ]
